### ISSUE TITLE
Highlight.js themes support

### ISSUE THREAD

**Issue by baransu** [pablohirafuji/elm-syntax-highlight#1]
First of all I want to thank you for great package 🎉. I haven't tested it in any project yet but it looks awesome. I started working on something similar but I haven't had enough time to finish it.
It will be a great fit for [elm-codepress](https://baransu.github.io/elm-codepress/example/) (use arrows if you want to test it out).

I was thinking if it's possible to be compatible with [highlight.js](https://github.com/isagalaev/highlight.js/) themes. They have very reach library of them and it's as simple as adding required `.css` file in `<head>` even from CDN.

I would be more than happy to contribute to this project 😃

**Comment by pablohirafuji** [comment]
Hey, elm-codepress is looking awesome! Can't wait to use it in some complex docs!

The reason why I didn't did it highlightjs theme compatible is that I think its themes are very complex. For example, there's a `hljs-tag` css class, and there's few languages that uses the `tag` syntax. And if there's a language that doesn't fit or a new syntax type, you will have to add that to all stylesheets or the nomenclature lose its sense.

I looked through some themes and realize that 7 colors is enough to make most of them. It's very easy to create themes with only 7 choices. Highlight.js have over [35 classes](http://highlightjs.readthedocs.io/en/latest/css-classes-reference.html).

But you made me think about it. I will try to make a highlightjs theme compatible render function. It will not be perfect, but I think it will be close enough :)

**Comment by baransu** [comment]
I think decision was right to not stick to highlight.js themes. It would be overkill to write compatible renderer. 

I think right now the most important part is to improve language parsing flow to simplify process of adding new languages. I will try to add Elixir syntax highlighting and I'll give you some feedback how it went :-)
