### ISSUE TITLE
Incorrect Hilightlighting in Xml Declarations

### ISSUE THREAD

**Issue by GarkGarcia** [pablohirafuji/elm-syntax-highlight#10]
As you can see in the first line of this example provided, the `xml` function is currently incorrectly highlighting [XML declarations](https://www.w3.org/TR/REC-xml/#sec-prolog-dtd), which are part of the official [XML 1.0 standards](https://www.w3.org/TR/REC-xml/).
![Screenshot_1](https://user-images.githubusercontent.com/37553739/62426557-90be2c80-b6bc-11e9-8550-00cd168e4a57.png)

**Comment by pablohirafuji** [comment]
Fixed in 3.1.1. Let me know if there is a problem.
