### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by aminnairi** [pablohirafuji/elm-syntax-highlight#11]
Hi there!

Is there any plans to support syntax highlight for JSON source-codes?

**Comment by brandly** [comment]
Have you tried the JavaScript syntax highlighting? It should work well

**Comment by pablohirafuji** [comment]
The JavaScript one should work well, but I added a JSON specific one. It should be faster and more accurate. Released on [3.2.0](https://package.elm-lang.org/packages/pablohirafuji/elm-syntax-highlight/latest).
