### ISSUE TITLE
elm-css support

### ISSUE THREAD

**Issue by BrianHicks** [pablohirafuji/elm-syntax-highlight#12]
Hey! I'd love to use this library in a site built with elm-css. Do you have any ideas about how to support that? I wonder if something like `ConsoleOptions` would work for all custom rendering:

```elm
viewCustom :
  { default : String -> a
  , style1 : String -> a -- the rest of styleN would be the same
  , highlight : a -> a -- assuming that the code being highlighted also needs to be separately rendered
  , addition : a -> a
  , deletion : a -> a
  }
  -> HCode
  -> a
```

**Comment by pablohirafuji** [comment]
This is a great idea. I will explore the viability and implement it.

**Comment by pablohirafuji** [comment]
Released on [3.3.0](https://package.elm-lang.org/packages/pablohirafuji/elm-syntax-highlight/3.3.0/). I don't know why, but the package page says it's not the latest release:

![2020-02-15](https://user-images.githubusercontent.com/15112020/74588866-edd95a00-4fde-11ea-8de9-8854bdeab439.png)

**Comment by brandly** [comment]
It does now! https://package.elm-lang.org/packages/pablohirafuji/elm-syntax-highlight/latest/

**Comment by pablohirafuji** [comment]
Nice, thanks @brandly! I will close the issue.

**Comment by BrianHicks** [comment]
thank you so much @pablohirafuji! This works wonderfully!
