### ISSUE TITLE
Feature request: generic "language unknown" support

### ISSUE THREAD

**Issue by Anton-4** [pablohirafuji/elm-syntax-highlight#13]
For an open source project I am working on it would be useful to have a generic option when the language is unknown.
I think this could be a common use case and would help users to keep the flow of their program tidy, not having to patch in code and styling that has to be manually updated if changes occur after updates of elm-syntax-highlight.

I can implement it myself if you'd like.

**Comment by pablohirafuji** [comment]
It's a great feature, I would love to accept a PR on this.

**Comment by Anton-4** [comment]
Excellent, I'll probably have it ready next week.
