### ISSUE TITLE
Exposing Theme module

### ISSUE THREAD

**Issue by kishlaya** [pablohirafuji/elm-syntax-highlight#6]
In the [example](https://github.com/pablohirafuji/elm-syntax-highlight/blob/master/demo/Main.elm) file, you have `import SyntaxHighlight.Theme as Theme` on line 11.

But this won't work, because `SyntaxHighlight.Theme` has not been exposed (and so it won't be able to find this module).

One straightforward fix is to add `SyntaxHighlight.Theme` in the list of [exposed modules](https://github.com/pablohirafuji/elm-syntax-highlight/blob/master/elm-package.json)

But looking at the structure of the package, I don't think so if this is a good solution?!

**Comment by pablohirafuji** [comment]
It was used in the example to show the theme's raw text, but it's not necessary to use the package. What are you trying to do?

**Comment by kishlaya** [comment]
I am a newbie so I'd to spent some time wondering why isn't the example compiling. I thought it would be best if the example to worked directly and so that someone else doesn't have to bother about it.
(Just wanted the example to compile without touching anything else)

**Comment by pablohirafuji** [comment]
Hmm I see. I agree with you, it's frustrating when things doesn't work the expected way. I will remove the need to import `SyntaxHighlight.Theme` from the example.

**Comment by kishlaya** [comment]
Thanks.

**Comment by pablohirafuji** [comment]
Removed the import to `SyntaxHighlight.Theme` on example. Thanks for the feedback!
