### ISSUE TITLE
elm 0.19

### ISSUE THREAD

**Issue by brandly** [pablohirafuji/elm-syntax-highlight#8]
as you've maybe heard, a new version of elm has been released. [this upgrade doc mentions](https://github.com/elm/compiler/blob/master/upgrade-docs/0.19.md#packages-moved), "`elm-tools/elm-parser` moved to `elm/parser`..."

i started to try this out. several items imported from `Parser` are no longer exposed, including `Count(..), oneOrMore, ignore, zeroOrMore, fail, source, delayedCommit`. at this point, [the example in the docs isn't even up to date](https://github.com/elm/parser/issues/7), so it may be too early to worry about upgrading this package.

i mostly wanted to get this on your radar, and document what i've found so far. hope you're doing well!

**Comment by pablohirafuji** [comment]
Hey, thanks! Yeah, I'm finishing other project, but will update this package asap. I really like the new changes of 0.19 and can't wait to see what coding with the new parser feels like :)

**Comment by pablohirafuji** [comment]
Updated to 0.19. The new parser is excellent! It's definitely an improvement. Thanks for the feedback! ;)
